version: "3.8"

services:
  app:
    image: node:18-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: "npm run dev"
    depends_on:
      - redis

  redis:
    image: redis:7
    volumes:
      - redis:/data
    ports:
      - 6379:6379

volumes:
  redis:
